[project]
name = "tukuaso-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "google-generativeai>=0.8.4",
    "requests>=2.32.3",
]
